name: Quotes APP

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build & test with Maven
        run: mvn clean verify
      
      - name: SonarQube Scan
        run: mvn sonar:sonar

      - name: Login to GHCR
        run: docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/quotebook-quotes-app
          docker build -t ${{ github.sha }}/quotebook-quotes-app .
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest

      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/quotebook-quotes-app
          docker push $IMAGE:${{ github.sha }}/quotebook-quotes-app
          docker push $IMAGE:latest